// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DB_Context))]
    partial class DB_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ENTITY.AsignacionTarea", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_ASIGNACION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsignacion"));

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_ASIGNACION");

                    b.Property<int>("IdAsignadoA")
                        .HasColumnType("integer")
                        .HasColumnName("ID_ASIGNADO_A");

                    b.Property<int>("IdAsignadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("ID_ASIGNADO_POR");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERIODO");

                    b.Property<int?>("IdRegla")
                        .HasColumnType("integer")
                        .HasColumnName("ID_REGLA");

                    b.Property<int>("IdTarea")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TAREA");

                    b.Property<string>("tipoAsignacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("TIPO_ASIGNACION");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdAsignadoA");

                    b.HasIndex("IdAsignadoPor");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdRegla");

                    b.HasIndex("IdTarea");

                    b.ToTable("ASIGNACION_TAREAS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Disponibilidad", b =>
                {
                    b.Property<int>("IdDisponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_DISPONIBILIDAD");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDisponibilidad"));

                    b.Property<decimal?>("CapacidadPorDia")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("CAPACIDAD_POR_DIA");

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("DIA_SEMANA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdDisponibilidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DISPONIBILIDAD", (string)null);
                });

            modelBuilder.Entity("ENTITY.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EMPRESA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("CORREO");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Direccion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("DIRECCION");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NIT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TELEFONO");

                    b.HasKey("IdEmpresa");

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EQUIPO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipo"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PROYECTO");

                    b.Property<int>("IdSupervisor")
                        .HasColumnType("integer")
                        .HasColumnName("ID_SUPERVISOR");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdSupervisor");

                    b.ToTable("EQUIPOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.EquipoUsuario", b =>
                {
                    b.Property<int>("IdEquipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EQUIPO_USUARIO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipoUsuario"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_ASIGNACION");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EQUIPO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdEquipoUsuario");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EQUIPO_USUARIOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Especializacion", b =>
                {
                    b.Property<int>("IdEspecializacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_ESPECIALIZACION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecializacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("NombreEspecializacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("NOMBRE_ESPECIALIZACION");

                    b.HasKey("IdEspecializacion");

                    b.ToTable("ESPECIALIZACIONES", (string)null);
                });

            modelBuilder.Entity("ENTITY.EvaluacionTarea", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EVALUACION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("COMENTARIO");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA");

                    b.Property<int>("IdTarea")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TAREA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("integer")
                        .HasColumnName("PUNTUACION");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdTarea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EVALUACION_TAREAS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_EVENTO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA");

                    b.Property<int?>("IdTarea")
                        .HasColumnType("integer")
                        .HasColumnName("ID_TAREA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TIPO_EVENTO");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdTarea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EVENTOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.MetricaUsuario", b =>
                {
                    b.Property<int>("IdMetrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_METRICA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMetrica"));

                    b.Property<decimal?>("CalificacionActual")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CALIFICACION_ACTUAL");

                    b.Property<decimal?>("CargaPromedio")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CARGA_PROMEDIO");

                    b.Property<decimal?>("Confiabilidad")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CONFIABILIDAD");

                    b.Property<decimal?>("CumplimientoPlazoPct")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("CUMPLIMIENTO_PLAZO_PCT");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERIODO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int?>("TareasAsignadas")
                        .HasColumnType("integer")
                        .HasColumnName("TAREAS_ASIGNADAS");

                    b.Property<int?>("TareasCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("TAREAS_COMPLETADAS");

                    b.HasKey("IdMetrica");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("METRICA_USUARIOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_NOTIFICACION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MENSAJE");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NOTIFICACIONES", (string)null);
                });

            modelBuilder.Entity("ENTITY.Periodo", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERIODO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPeriodo"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_FIN");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdPeriodo");

                    b.ToTable("PERIODOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PROYECTO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProyecto"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_FIN");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<int?>("IdSupervisor")
                        .HasColumnType("integer")
                        .HasColumnName("ID_SUPERVISOR");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal?>("Progreso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PROGRESO");

                    b.HasKey("IdProyecto");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSupervisor");

                    b.ToTable("PROYECTOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.ReglaAsignacion", b =>
                {
                    b.Property<int>("IdRegla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_REGLA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegla"));

                    b.Property<int?>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal?>("PesoCalificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PESO_CALIFICACION");

                    b.Property<decimal?>("PesoCarga")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PESO_CARGA");

                    b.Property<decimal?>("PesoDisponibilidad")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("PESO_DISPONIBILIDAD");

                    b.Property<decimal?>("PesoProductividad")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("PESO_PRODUCTIVIDAD");

                    b.HasKey("IdRegla");

                    b.ToTable("REGLA_ASIGNACION", (string)null);
                });

            modelBuilder.Entity("ENTITY.RelacionJerarquica", b =>
                {
                    b.Property<int>("IdRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_RELACION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRelacion"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_FIN");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EMPLEADO");

                    b.Property<int>("IdJefe")
                        .HasColumnType("integer")
                        .HasColumnName("ID_JEFE");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdJefe");

                    b.ToTable("RELACION_JERARQUICA", (string)null);
                });

            modelBuilder.Entity("ENTITY.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_TAREA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_LIMITE");

                    b.Property<int>("IdEspecializacion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_ESPECIALIZACION");

                    b.Property<int?>("Prioridad")
                        .HasColumnType("integer")
                        .HasColumnName("PRIORIDAD");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TITULO");

                    b.Property<string>("estadoTarea")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ESTADO");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdEspecializacion");

                    b.ToTable("TAREAS", (string)null);
                });

            modelBuilder.Entity("ENTITY.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("Activo")
                        .HasColumnType("integer")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("APELLIDO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<int>("NivelJerarquico")
                        .HasColumnType("integer")
                        .HasColumnName("NIVEL_JERARQUICO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ROL");

                    b.Property<decimal?>("Salario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("SALARIO");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("CONTRASENA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("ENTITY.UsuarioEspecializacion", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("IdEspecializacion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_ESPECIALIZACION");

                    b.HasKey("IdUsuario", "IdEspecializacion");

                    b.ToTable("USUARIO_ESPECIALIZACION", (string)null);
                });

            modelBuilder.Entity("ENTITY.AsignacionTarea", b =>
                {
                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAsignadoA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAsignadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ENTITY.Periodo", null)
                        .WithMany()
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.ReglaAsignacion", null)
                        .WithMany()
                        .HasForeignKey("IdRegla");

                    b.HasOne("ENTITY.Tarea", null)
                        .WithMany()
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Disponibilidad", b =>
                {
                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Equipo", b =>
                {
                    b.HasOne("ENTITY.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdSupervisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.EquipoUsuario", b =>
                {
                    b.HasOne("ENTITY.Equipo", null)
                        .WithMany()
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.EvaluacionTarea", b =>
                {
                    b.HasOne("ENTITY.Tarea", null)
                        .WithMany()
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Evento", b =>
                {
                    b.HasOne("ENTITY.Tarea", null)
                        .WithMany()
                        .HasForeignKey("IdTarea");

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.MetricaUsuario", b =>
                {
                    b.HasOne("ENTITY.Periodo", null)
                        .WithMany()
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Notificacion", b =>
                {
                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Proyecto", b =>
                {
                    b.HasOne("ENTITY.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdSupervisor")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ENTITY.RelacionJerarquica", b =>
                {
                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ENTITY.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdJefe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ENTITY.Tarea", b =>
                {
                    b.HasOne("ENTITY.Especializacion", "Especializacion")
                        .WithMany()
                        .HasForeignKey("IdEspecializacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especializacion");
                });
#pragma warning restore 612, 618
        }
    }
}
